# Generated by Django 3.0.6 on 2020-05-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200511_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='desc',
            field=models.TextField(blank=True, help_text='Enter the recipe steps.'),
        ),
    ]
